// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpomC47ztVeqdDobIgBjIPJsd0OfqPtZU',
    appId: '1:671682979243:web:0ff8ab9e3568a601661eee',
    messagingSenderId: '671682979243',
    projectId: 'management-flutter-app',
    authDomain: 'management-flutter-app.firebaseapp.com',
    storageBucket: 'management-flutter-app.appspot.com',
    measurementId: 'G-E2WXN7X98E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAmGUUucnFPvT2TpnF34-1PsRY8FR2fbY',
    appId: '1:671682979243:android:da2068b2dbb9338f661eee',
    messagingSenderId: '671682979243',
    projectId: 'management-flutter-app',
    storageBucket: 'management-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf4ltYfd_6fVOmBMeAIOJkKtvFYiT3u-0',
    appId: '1:671682979243:ios:a46edd91581506d7661eee',
    messagingSenderId: '671682979243',
    projectId: 'management-flutter-app',
    storageBucket: 'management-flutter-app.appspot.com',
    iosClientId: '671682979243-eehs4t7icrtu7sihk7fjf3hme1m0k6vl.apps.googleusercontent.com',
    iosBundleId: 'vn.com.edu.itss.managementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf4ltYfd_6fVOmBMeAIOJkKtvFYiT3u-0',
    appId: '1:671682979243:ios:a46edd91581506d7661eee',
    messagingSenderId: '671682979243',
    projectId: 'management-flutter-app',
    storageBucket: 'management-flutter-app.appspot.com',
    iosClientId: '671682979243-eehs4t7icrtu7sihk7fjf3hme1m0k6vl.apps.googleusercontent.com',
    iosBundleId: 'vn.com.edu.itss.managementApp',
  );
}
